// <auto-generated />
using System;
using BattleHub.ProfileService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleHub.ProfileService.Api.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BattleHub.ProfileService.Api.Models.Game", b =>
                {
                    b.Property<string>("GameType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("game_type");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("RequiredPermission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("required_permission");

                    b.HasKey("GameType");

                    b.ToTable("games", (string)null);

                    b.HasData(
                        new
                        {
                            GameType = "typing",
                            Enabled = true,
                            Name = "Typing Battle",
                            RequiredPermission = "games.typing.play"
                        },
                        new
                        {
                            GameType = "trivia",
                            Enabled = true,
                            Name = "Trivia Battle",
                            RequiredPermission = "games.trivia.play"
                        },
                        new
                        {
                            GameType = "memory",
                            Enabled = true,
                            Name = "Memory Match",
                            RequiredPermission = "games.memory.play"
                        });
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Models.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.HasKey("Code");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "matches.create",
                            Description = "Crear salas de partidas"
                        },
                        new
                        {
                            Code = "games.typing.play",
                            Description = "Jugar a Typing Battle"
                        },
                        new
                        {
                            Code = "games.trivia.play",
                            Description = "Jugar a Trivia Battle"
                        },
                        new
                        {
                            Code = "games.memory.play",
                            Description = "Jugar a Memory Match"
                        });
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("PermissionProfile", b =>
                {
                    b.Property<string>("PermissionsCode")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfilesId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionsCode", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("profile_permissions", (string)null);
                });

            modelBuilder.Entity("PermissionProfile", b =>
                {
                    b.HasOne("BattleHub.ProfileService.Api.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleHub.ProfileService.Api.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
