// <auto-generated />
using System;
using BattleHub.ProfileService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleHub.ProfileService.Api.Data.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.Game", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("RequiredPermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("required_permission_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.HasIndex("RequiredPermissionCode");

                    b.ToTable("games", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "typing",
                            Description = "Competencia de velocidad y precisión de escritura.",
                            IsActive = true,
                            Name = "Typing Battle",
                            RequiredPermissionCode = "games.typing.play",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "trivia",
                            Description = "Preguntas y respuestas por categorías contra otros jugadores.",
                            IsActive = true,
                            Name = "Trivia Battle",
                            RequiredPermissionCode = "games.trivia.play",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "memory",
                            Description = "Juego de memoria: encontrar los pares en el menor tiempo posible.",
                            IsActive = true,
                            Name = "Memory Match",
                            RequiredPermissionCode = "games.memory.play",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("GrantedByDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("granted_by_default");

                    b.HasKey("Code");

                    b.HasIndex("GrantedByDefault")
                        .HasDatabaseName("ix_permissions_granted_by_default");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "matches.create",
                            Description = "Crear partidas en el lobby de Matchmaking",
                            GrantedByDefault = true
                        },
                        new
                        {
                            Code = "games.typing.play",
                            Description = "Jugar Typing Battle",
                            GrantedByDefault = true
                        },
                        new
                        {
                            Code = "games.trivia.play",
                            Description = "Jugar Trivia Battle",
                            GrantedByDefault = true
                        },
                        new
                        {
                            Code = "games.memory.play",
                            Description = "Jugar Memory Match",
                            GrantedByDefault = true
                        });
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("auth0_user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_auth0_user_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_email");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.UserProfilePermission", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_profile_id");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("permission_code");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("granted_at_utc");

                    b.HasKey("UserProfileId", "PermissionCode");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_user_profile_permissions_permission_code");

                    b.ToTable("user_profile_permissions", (string)null);
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.Game", b =>
                {
                    b.HasOne("BattleHub.ProfileService.Api.Domain.Entities.Permission", "RequiredPermission")
                        .WithMany()
                        .HasForeignKey("RequiredPermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_required_permission");

                    b.Navigation("RequiredPermission");
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.UserProfilePermission", b =>
                {
                    b.HasOne("BattleHub.ProfileService.Api.Domain.Entities.Permission", "Permission")
                        .WithMany("UserProfiles")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_permissions_permission");

                    b.HasOne("BattleHub.ProfileService.Api.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_permissions_user_profile");

                    b.Navigation("Permission");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.Permission", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("BattleHub.ProfileService.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
